# Generated by Django 5.2.6 on 2025-11-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque Disponível')),
                ('categoria', models.CharField(choices=[('JOGO', 'Jogo'), ('CONSOLE', 'Console'), ('ACESSORIO', 'Acessório')], default='JOGO', max_length=10, verbose_name='Categoria')),
                ('plataforma', models.CharField(choices=[('PS5', 'PlayStation 5'), ('PS4', 'PlayStation 4'), ('XBOX_SERIES', 'Xbox Series S/X'), ('XBOX_ONE', 'Xbox One'), ('NINTENDO_SWITCH', 'Nintendo Switch'), ('PC', 'PC'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Plataforma')),
                ('imagem_url', models.URLField(default='https://placehold.co/600x400/374151/ffffff?text=Produto', max_length=2000, verbose_name='URL da Imagem Principal')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
