# Generated by Django 5.2.6 on 2025-11-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_produto_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem Principal do Produto'),
        ),
    ]
