# Generated by Django 5.2.6 on 2025-11-27 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_produto_imagem_url_produto_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='classificacao_etaria',
            field=models.CharField(blank=True, choices=[('L', 'Livre para todos'), ('+10', '+10 Anos'), ('+14', '+14 Anos'), ('+16', '+16 Anos'), ('+18', '+18 Anos (Adulto)')], default='L', max_length=5, null=True, verbose_name='Classificação Etária'),
        ),
        migrations.AddField(
            model_name='produto',
            name='compatibilidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compatibilidade (Acessório)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cpu_gpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU/GPU (Console)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gênero (Jogo)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memória RAM (Console)'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200, verbose_name='Produto Comprado')),
                ('produto_preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Compra')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_comprados', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('vendedor_original', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Original')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_compra'],
            },
        ),
    ]
